### PR TITLE
Added Classification into brands heirarchy

### PR DESCRIPTION
**Pull request by scott-ace-newton**
Tree is now Brand->Classification->Concept->Thing

### CODE REVIEW

**Comment by sjwells** [comment]
I'd expect the tests to have to be changed too - there is a test for the Brand types.

Looking at them, they define which labels a type will have - so Brands needs to have Classification added to the labels, and to the expected types.

**Comment by martingartonft** [comment]
lgtm

**Comment by scott-ace-newton** [comment]
@sjwells I'm guessing the tests are bad because the circleci build passed. They pass whether I add classification in or not

**Comment by sjwells** [comment]
Yep - I will fix up the code/tests to not have that feature :)

But I'll do that as a separate PR. Go ahead with merging this.

**Pull request merged**
